CREATE  OR REPLACE WAREHOUSE SECOND_WH 
WITH 
    WAREHOUSE_SIZE = XSMALL
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    AUTO_SUSPEND = 300
    SCALING_POLICY = 'Economy'
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'This is our second warehouse'

ALTER WAREHOUSE SECOND_WH RESUME;

ALTER WAREHOUSE SECOND_WH 
SET 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 90;

DROP WAREHOUSE SECOND_WH ;